
create table if not exists oauth_client_details (
  client_id VARCHAR(256) PRIMARY KEY,
  resource_ids VARCHAR(256),
  client_secret VARCHAR(256),
  scope VARCHAR(256),
  authorized_grant_types VARCHAR(256),
  web_server_redirect_uri VARCHAR(256),
  authorities VARCHAR(256),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additional_information VARCHAR(4096),
  autoapprove VARCHAR(256)
);

insert into oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types,
                                  web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity,
                                  additional_information, autoapprove)
values ('myuser', '', '$2a$10$wxmTX6lU3ZTK9JVn4wRByuFR6clme74mlXytAOXe2wZI5KW.IYlku', 'read,write', 'password,client_details,refresh_token', '', '', 3600, 3600, '{}', true);

INSERT INTO public.users
(id, "password", username, status)
VALUES(1, '$2a$10$ySBaY4qUaZ2c8w/BEufnnOaTFlGbZDGnEXs3vG71m96iPbusboixC', 'admin', 'ACTIVE');


INSERT INTO public."role"
(id, description, role_name, status)
VALUES(1, 'Admin', 'ROLE_ADMIN', 'ACTIVE');


INSERT INTO public.user_role
(id, role_id, user_id)
VALUES(1, 1, 1);

-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	"password" varchar(255) NULL,
	phone varchar(255) NULL,
	profile varchar(255) NULL,
	username varchar(255) NULL,
	status varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE INDEX email_index ON public.users USING btree (email);



